name: Flutter Web Build & Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build Flutter Web e Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.3"
          channel: "stable"
          cache: true

      - name: Instalar dependencias
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href=/

      - name: Criar vercel.json na pasta de build
        run: |
          echo "{\"version\":2,\"buildCommand\":null,\"outputDirectory\":\".\",\"installCommand\":null,\"framework\":null,\"routes\":[{\"handle\":\"filesystem\"},{\"src\":\"/(.*)\",\"dest\":\"/index.html\"}]}" > ./build/web/vercel.json

      - name: Instalar Vercel CLI
        run: npm install -g vercel@latest

      - name: Link e Deploy para Vercel
        run: |
          cd ./build/web
          vercel link --yes --token=${{ secrets.VERCEL_TOKEN }} --project=caparroz --scope=despachantecaparroz
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes